version: '3.3'
services:
  stirling-pdf:
    container_name: Stirling-PDF
    build: .
  #  image: frooodle/s-pdf:latest
    deploy:
      resources:
        limits:
          memory: 4G
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/v1/info/status | grep -q 'UP' && curl -fL http://localhost:8080/ | grep -qv 'Please sign in'"]
      interval: 5s
      timeout: 10s
      retries: 16
    ports:
      - 8082:8080
    volumes:
      - /stirling/latest/data:/usr/share/tessdata:rw
      - /stirling/latest/config:/configs:rw
      - /stirling/latest/logs:/logs:rw
    environment:
      DOCKER_ENABLE_SECURITY: "false"
      SECURITY_ENABLELOGIN: "false"
      LANGS: "en_US, fr_FR"
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: "true"
      SYSTEM_DEFAULTLOCALE: en-US
      UI_APPNAME: ONYX PDF
      UI_HOMEDESCRIPTION: Free all-in-one PDF editor brought to you by Onyx FIN Accounting
      UI_APPNAMENAVBAR: ONYX PDF
      SYSTEM_MAXFILESIZE: "100"
      METRICS_ENABLED: "true"
      SYSTEM_GOOGLEVISIBILITY: "true"
      ENDPOINTS_TO_REMOVE: "ocr-pdf,pipeline"
    restart: on-failure:5
