name: Docker Compose Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Compose Services
        run: docker compose build


      - name: Stop Existing Docker Compose Services
        run: docker compose down

      - name: Start Docker Compose Services
        run: docker compose up -d
        
      - name: Remove Unused Docker Images
        run: docker image prune -f

      - name: Check Docker Compose Services Status
        run: docker compose ps -a
